### ISSUE TITLE
ACE for text classification

### ISSUE THREAD

**Issue by patelrajnath** [Alibaba-NLP/ACE#15]
Hi there,

How complex it would be to use ACE for text classification. If possible, could you please add a working example for the same.

Regards
Raj

**Comment by wangxinyu0922** [comment]
Hi,

I have no experience for implementing text classificiation models. If you want to implement the code by yourself, I have following suggestions:

 - [text_classification_model.py](https://github.com/Alibaba-NLP/ACE/blob/74ac8ba44b5e2e00b34caf0098f7ee8b1d082892/flair/models/text_classification_model.py#L82-L84) is the code for implementing text classification model from flair. 
 - At line 82-84, the code extracts document embeddings instead of word embeddings for the model. Therefore, you may need to decide which part of embedding represents the text embedding. For example, the representation of `[CLS]` is used by BERT for text classification. Some of the embeddings like Flair embeddings is difficult to decide text embeddings. It could be easier using the pooled/mean embeddings over tokens. You can find the implementation at [embeddings.py](https://github.com/Alibaba-NLP/ACE/blob/74ac8ba44b5e2e00b34caf0098f7ee8b1d082892/flair/embeddings.py#L3728-L4316). But personally I suggest you just implement the function at the forward function at [text_classification_model.py](https://github.com/Alibaba-NLP/ACE/blob/74ac8ba44b5e2e00b34caf0098f7ee8b1d082892/flair/models/text_classification_model.py#L78-L89).
 - In general, I suggest you may follow the embedding selection function at [sequence_tagger_model.py](https://github.com/Alibaba-NLP/ACE/blob/74ac8ba44b5e2e00b34caf0098f7ee8b1d082892/flair/models/sequence_tagger_model.py#L821-L873) to implement ACE  at[text_classification_model.py](https://github.com/Alibaba-NLP/ACE/blob/74ac8ba44b5e2e00b34caf0098f7ee8b1d082892/flair/models/text_classification_model.py#L78-L89). Then just calculate pooled/mean embeddings over the **selected** embedding candidates as the text representation for the `sentence_tensor`. 

Best.

**Comment by patelrajnath** [comment]
Thanks @wangxinyu0922 

I'll have a look at it and see how it goes. 

Regards
Raj

**Comment by nguyenbh** [comment]
Close this issue since Xinyu's comment seems to resolve the OP question.
