### ISSUE TITLE
Issue with running requirements.txt

### ISSUE THREAD

**Issue by EricJi150** [Alibaba-NLP/ACE#37]

**Comment by spacemonqi** [comment]
Many package dependencies are deprecated. Will the requirements eventually be updated for newer Python versions? 

Furthermore, installing the requirements gives 

ERROR: Cannot install -r requirements.txt (line 4) and conllu==4.4 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested conllu==4.4
    allennlp 0.9.0 depends on conllu==1.3.1

The conflict is caused by:
    The user requested numpy==1.15.1
    allennlp 0.9.0 depends on numpy
    blis 0.2.4 depends on numpy>=1.15.0
    bpemb 0.3.0 depends on numpy
    elmoformanylangs 0.0.2 depends on numpy
    gensim 3.8.1 depends on numpy>=1.11.3
    h5py 2.8.0 depends on numpy>=1.7
    keras-applications 1.0.8 depends on numpy>=1.9.1
    keras-preprocessing 1.1.0 depends on numpy>=1.9.1
    matplotlib 3.1.3 depends on numpy>=1.11
    mxnet 1.5.0 depends on numpy<2.0.0 and >1.16.0
